// <auto-generated />
using System;
using BillSplitter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillSplitter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillSplitterDbContext))]
    [Migration("20260329065316_AddBuddiesAndExpenses")]
    partial class AddBuddiesAndExpenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillSplitter.Domain.Entities.Buddy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_user_id");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_buddies");

                    b.HasIndex("LinkedUserId")
                        .HasDatabaseName("ix_buddies_linked_user_id");

                    b.HasIndex("OwnerId", "Email")
                        .IsUnique()
                        .HasDatabaseName("idx_buddies_owner_email");

                    b.ToTable("buddies", (string)null);
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("LastResentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_resent_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("verification_code");

                    b.HasKey("Id")
                        .HasName("pk_email_verifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_email_verifications_user_id");

                    b.HasIndex("VerificationCode")
                        .HasDatabaseName("idx_email_verifications_code");

                    b.ToTable("email_verifications", (string)null);
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("PaidByBuddyId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_buddy_id");

                    b.Property<Guid?>("PaidByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_user_id");

                    b.Property<int>("SplitType")
                        .HasColumnType("integer")
                        .HasColumnName("split_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_expenses_created_by_user_id");

                    b.HasIndex("PaidByBuddyId")
                        .HasDatabaseName("ix_expenses_paid_by_buddy_id");

                    b.HasIndex("PaidByUserId")
                        .HasDatabaseName("ix_expenses_paid_by_user_id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.ExpenseSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BuddyId")
                        .HasColumnType("uuid")
                        .HasColumnName("buddy_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_expense_splits");

                    b.HasIndex("BuddyId")
                        .HasDatabaseName("ix_expense_splits_buddy_id");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("ix_expense_splits_expense_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_expense_splits_user_id");

                    b.ToTable("expense_splits", (string)null);
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.Buddy", b =>
                {
                    b.HasOne("BillSplitter.Domain.Entities.User", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_buddies_users_linked_user_id");

                    b.HasOne("BillSplitter.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_buddies_users_owner_id");

                    b.Navigation("LinkedUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.EmailVerification", b =>
                {
                    b.HasOne("BillSplitter.Domain.Entities.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.Expense", b =>
                {
                    b.HasOne("BillSplitter.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_users_created_by_user_id");

                    b.HasOne("BillSplitter.Domain.Entities.Buddy", "PaidByBuddy")
                        .WithMany()
                        .HasForeignKey("PaidByBuddyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_buddies_paid_by_buddy_id");

                    b.HasOne("BillSplitter.Domain.Entities.User", "PaidByUser")
                        .WithMany()
                        .HasForeignKey("PaidByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_users_paid_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("PaidByBuddy");

                    b.Navigation("PaidByUser");
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.ExpenseSplit", b =>
                {
                    b.HasOne("BillSplitter.Domain.Entities.Buddy", "Buddy")
                        .WithMany()
                        .HasForeignKey("BuddyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expense_splits_buddies_buddy_id");

                    b.HasOne("BillSplitter.Domain.Entities.Expense", "Expense")
                        .WithMany("ExpenseSplits")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_splits_expenses_expense_id");

                    b.HasOne("BillSplitter.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expense_splits_users_user_id");

                    b.Navigation("Buddy");

                    b.Navigation("Expense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.Expense", b =>
                {
                    b.Navigation("ExpenseSplits");
                });

            modelBuilder.Entity("BillSplitter.Domain.Entities.User", b =>
                {
                    b.Navigation("EmailVerifications");
                });
#pragma warning restore 612, 618
        }
    }
}
